import type { Metadata } from "next";

import localFont from "next/font/local";

import "./globals.css";

const plusJakartaSans = localFont({
  src: [
    {
      path: "../fonts/PlusJakartaSans-Variable.woff2",
      weight: "100 900",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
